### ISSUE TITLE
사용자 UI 구성

### ISSUE THREAD

**Issue by dmdgpdi** [IGRUS-INHA/2022_01_Study_N_Project_InhaFit_FE#1]
## Feature Description

- 먼저 피그마의 디자인을 바탕으로 ui부터 구성하려합니다.

## Todo list

- [ ] 회원가입 ui 작성
- [ ] 회원정보 ui 작성
- [ ] 로그인 ui 작성
- [ ] 회원탈퇴 ui
